version: '3.7'

volumes:
  postgres:
  celery:
  redis:

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fakecsvs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
  celery:
    build: ./
    volumes:
      - ./:/app
      - /tmp/hq-backend:/tmp
    depends_on:
      - db
      - redis
    command: bash -c "python3 manage.py migrate && celery -A config worker -l info"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
  redis:
    image: redis:6.0.6-alpine
    volumes:
      - redis/:/data
    command: redis-server
    ports:
      - 6379