# Generated by Django 3.1.7 on 2021-02-20 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан в "),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Готов к скачиванию"),
                            ("processing", "В работе"),
                            ("failed", "Ошибка"),
                        ],
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="schemas/",
                        verbose_name="Схема",
                    ),
                ),
            ],
            options={"verbose_name": "Схема", "verbose_name_plural": "Схемы"},
        ),
        migrations.CreateModel(
            name="ColumnInSchema",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("integer", "Number range"),
                            ("date", "Date time"),
                            ("email", "E-mail"),
                            ("phone", "Phone number"),
                            ("job", "Job position"),
                        ],
                        max_length=30,
                        verbose_name="Тип данных",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Порядок столбцов",
                    ),
                ),
                (
                    "quantity_range_lower",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Нижняя граница диапазона чисел",
                    ),
                ),
                (
                    "quantity_range_upper",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Верхняя граница диапазона чисел",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schemas.schema",
                        verbose_name="Схема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столбец в схеме",
                "verbose_name_plural": "Столбцы в схеме",
            },
        ),
    ]
