# Generated by Django 3.1.7 on 2021-02-20 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schema",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        )
    ]
