# Generated by Django 3.1.7 on 2021-02-20 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schemas", "0004_auto_20210220_1309"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schemas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        )
    ]
